USE [master]
GO

/****** Object:  Database [IAGenerativaDB]    Script Date: 9/6/2025 15:28:26 ******/
CREATE DATABASE [IAGenerativaDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'IAGenerativaDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS01\MSSQL\DATA\IAGenerativaDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'IAGenerativaDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS01\MSSQL\DATA\IAGenerativaDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [IAGenerativaDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [IAGenerativaDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [IAGenerativaDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [IAGenerativaDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [IAGenerativaDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [IAGenerativaDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [IAGenerativaDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [IAGenerativaDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [IAGenerativaDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [IAGenerativaDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [IAGenerativaDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [IAGenerativaDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [IAGenerativaDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [IAGenerativaDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [IAGenerativaDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [IAGenerativaDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [IAGenerativaDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [IAGenerativaDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [IAGenerativaDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [IAGenerativaDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [IAGenerativaDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [IAGenerativaDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [IAGenerativaDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [IAGenerativaDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [IAGenerativaDB] SET  MULTI_USER 
GO

ALTER DATABASE [IAGenerativaDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [IAGenerativaDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [IAGenerativaDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [IAGenerativaDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [IAGenerativaDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [IAGenerativaDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [IAGenerativaDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [IAGenerativaDB] SET  READ_WRITE 
GO


