CREATE TABLE FraseClasificacion (
    Id INT IDENTITY PRIMARY KEY,
    Texto NVARCHAR(512) NOT NULL,
    ClasificacionId INT NOT NULL,
    FOREIGN KEY (ClasificacionId) REFERENCES Clasificacion(Id)
);

-- Formales
INSERT INTO FraseClasificacion (Texto, ClasificacionId) VALUES
('Estimado cliente, le informamos que su pedido fue procesado.', 1),
('Por favor, remita la documentación solicitada a la brevedad.', 1),
('Le agradecemos su consulta y quedamos a disposición.', 1),
('Nos dirigimos a usted para comunicarle la siguiente novedad.', 1),
('Saludos cordiales, quedamos atentos a cualquier requerimiento.', 1),
('Le solicitamos tenga a bien revisar la información adjunta.', 1),
('Le recordamos que el plazo de entrega es de 48 horas.', 1),
('Agradecemos su preferencia y confianza en nuestros servicios.', 1),
('Adjuntamos el informe solicitado.', 1),
('Por este medio le enviamos la factura correspondiente.', 1),
('Quedamos atentos a cualquier inquietud que pudiera surgir.', 1),
('Le rogamos confirmar la recepción del presente correo.', 1),
('Es un placer ponernos en contacto con usted.', 1),
('Nos permitimos informarle sobre los nuevos procedimientos.', 1),
('Agradecemos su atención y quedamos a su disposición.', 1),
('Le saludamos muy atentamente.', 1),
('Por favor, no dude en consultarnos ante cualquier duda.', 1),
('En respuesta a su requerimiento, le adjuntamos la documentación.', 1),
('Le informamos que su solicitud ha sido recibida con éxito.', 1),
('Esperamos que la información brindada sea de su utilidad.', 1),
('Le enviamos un cordial saludo.', 1),
('Le comunicamos que su pedido está en proceso.', 1),
('Por favor, confirme la recepción de este mensaje.', 1),
('Agradecemos su confianza.', 1),
('Nos encontramos a su disposición para cualquier consulta.', 1),
('Quedamos atentos a cualquier requerimiento adicional.', 1),
('Le saludamos cordialmente.', 1),
('Por favor, tome en cuenta las condiciones adjuntas.', 1),
('En caso de dudas, comuníquese con nuestro soporte.', 1),
('Gracias por elegir nuestros servicios.', 1),
('Le informamos que el trámite se encuentra finalizado.', 1),
('Reciba un cordial saludo.', 1),
('Agradecemos su comunicación.', 1),
('Su satisfacción es nuestra prioridad.', 1),
('Hemos recibido su reclamo y será atendido a la brevedad.', 1),
('Por favor, no dude en contactarnos.', 1),
('Le informamos que sus datos han sido actualizados.', 1),
('Nos ponemos a su disposición para futuras consultas.', 1),
('Reciba un afectuoso saludo.', 1),
('Le solicitamos responder este mensaje para confirmar la operación.', 1),
('Por la presente, le informamos...', 1),
('Adjuntamos el presupuesto solicitado.', 1),
('Hemos registrado su pedido.', 1),
('Agradecemos su interés.', 1),
('Gracias por contactarnos.', 1),
('Le deseamos un excelente día.', 1),
('Por favor, revise el archivo adjunto.', 1),
('Quedamos a la espera de su respuesta.', 1),
('Le agradecemos su tiempo y consideración.', 1),
('Estamos a su disposición para lo que necesite.', 1);


-- Informales
INSERT INTO FraseClasificacion (Texto, ClasificacionId) VALUES
('Che, ya te mandé el archivo!', 2),
('Dale, nos vemos después.', 2),
('Mandame el archivo cuando puedas.', 2),
('Hola! Qué hacés?', 2),
('Pasame la data así lo hago.', 2),
('¿Tenés un minuto para charlar?', 2),
('¿Vamos a tomar algo?', 2),
('Te veo a la tarde.', 2),
('Me avisás cuando llegues?', 2),
('No te olvides de traer las cosas.', 2),
('Hablamos más tarde.', 2),
('¿Qué onda?', 2),
('¿Me prestás el libro?', 2),
('Mirá lo que te pasé!', 2),
('Cualquier cosa, avisame.', 2),
('Te espero abajo.', 2),
('Ya fue, hagámoslo mañana.', 2),
('¿Venís al cumple?', 2),
('No puedo creer lo que pasó.', 2),
('Apenas puedas, avisame.', 2),
('Nos juntamos el finde?', 2),
('¿Tenés la tarea?', 2),
('Dale que llegamos tarde.', 2),
('¿Vamos juntos?', 2),
('Si te pinta, avisá.', 2),
('No te preocupes, después lo vemos.', 2),
('Te cuento después.', 2),
('¿Salimos a comer?', 2),
('Pasate por casa.', 2),
('¿Te animás?', 2),
('Nos hablamos!', 2),
('¿Todo bien por ahí?', 2),
('¿Te copás?', 2),
('Cuando puedas, respondeme.', 2),
('No pasa nada, tranqui.', 2),
('Ya te paso el link.', 2),
('Fijate y decime.', 2),
('Nos vemos mañana.', 2),
('¿Está todo listo?', 2),
('¿Me ayudás con esto?', 2),
('Me olvidé de contarte algo.', 2),
('Andá tranquilo.', 2),
('¿Listo para salir?', 2),
('Después arreglamos.', 2),
('Acordate de lo que hablamos.', 2),
('¿Cuándo nos vemos?', 2),
('Te espero en la esquina.', 2),
('No sé, vos decime.', 2),
('¿Querés venir?', 2),
('Ponete cómodo.', 2),
('Lo hacemos rápido y ya está.', 2);
